-
  name: Deployment
  hosts: localhost
  tasks:

    - name: stop previous container with same name
      command: docker stop petstore-webapp-container
      ignore_errors: yes

    - name: remove previous container with same name
      command: docker rm petstore-webapp-container
      ignore_errors: yes

    - name: remove previous image with same name
      command: docker rmi engabdullah1909/jpetstore-webapp
      ignore_errors: yes

    - name: building the image
      command: docker build -t engabdullah1909/jpetstore-webapp .

    - name: push the image to Docker-hub
      command: docker push engabdullah1909/jpetstore-webapp

    - name: run a container from pushed image
      command: docker run -d -p 8089:8080 --name petstore-webapp-container engabdullah1909/jpetstore-webapp
