global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'tomcat-jmx'
    static_configs:
      - targets: ['petstore-webapp-container:8086']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
